### ISSUE TITLE
如何让他支持指定的主键

### ISSUE THREAD

**Issue by gkjolin** [yanghuan/proton#1]
现在直接都是生成一个大的list 如何才能制定list的key

**Comment by yanghuan** [comment]
excel 的结构每一行是一行数据，导出时自然就是一个数组的结构，如果有一列是主键的话，可以在读取导出配置时，将数组映射到字典，proton 只是一个导出工作，不涉及这部分工作。这部分工作可以在自动生成读取的代码框架中处理。

‘’‘
在自动生成的配置读取代码的框架中可通过继承的方式在派生类中进行检查、关联、重组织表结构等，具体可参考CSharpGeneratorForProton
’‘’
https://github.com/yanghuan/CSharpGeneratorForProton

**Comment by gkjolin** [comment]
def newline(count):
    return '\n' + '  ' * count
      
  if isinstance(obj, int) or isinstance(obj, float) or isinstance(obj, str):
    yield json.dumps(obj, ensure_ascii = False)
  else:
    indent += 1
    yield '{'
    islist = isinstance(obj, list)
    isfirst = True
    for i in obj:
      if isfirst:
        isfirst = False
      else:
        yield ','
      yield newline(indent)
      if not islist:
        k = i
        i = obj[k]
        yield k 
        yield ' = '                
      for part in tolua(i, indent):
        yield part
    indent -= 1
    yield newline(indent)
    yield '}'  在生成lua的时候 貌似是从这里生成的！ 我在/CSharpGeneratorForProton没有发现有生成的相关内容呀！

**Comment by gkjolin** [comment]
你能不能提供一个！lua的话 加入不提供设置主键的话 有的时候还是很有局限性的

**Comment by yanghuan** [comment]
在导出工具中提供这个功能是不合理的，这个是需要在读取时，自己做结构变换，将数组变换成字典，我项目中读取lua 时这个处理
“”“
local  array = LoadTemplate("HerosTemplate")
HerosConf = TemplateToConfTable(array, function (i)
    return i.Id
end)
”“”
你可能还需要进行检查、关联、重组织表结构，这些功能不适合在导出工具中提供，都需要你你在读取时
自行处理，很多导出工具处理了这部分的功能，结果变得臃肿和难以使用，这是有仔细考量的，希望你能理解~~
