### ISSUE TITLE
关于结构体 : 数组 , 分割的问题。

### ISSUE THREAD

**Issue by scc172fly** [yanghuan/proton#11]
最近对话系统比较简单，想想应该能用此工具可以解决，有中文和英文两个版本，中文版版本还好，英文版本就转不出来了。大佬，有时间可以看看我的这个需求，但对话系统可能用这个配置也不是很合理，若可以实现当然最好啦，就让策划鼓捣了，我不去unity里边写个产出配置的工具了。我提供了一个Excel样例。 
[Dialogue.xlsx](https://github.com/yanghuan/proton/files/5754447/Dialogue.xlsx)

**Comment by yanghuan** [comment]
需要转义,见下面的文档段落中斜体部分
https://github.com/yanghuan/proton/wiki/document_zh#3%E5%AD%97%E6%AE%B5%E7%B1%BB%E5%9E%8B
