### ISSUE TITLE
关于导出文件输出目录的问题

### ISSUE THREAD

**Issue by scc172fly** [yanghuan/proton#5]
tools 只能放到 excel 文件加下才可以导出配置文件，能力有限，想把配置和工具分离，没能解决。

现在我有这么个需求：
1、只用一个 tools，有很多模块共用此 tools;
2、每个模块包含很多的配置文件；
3、目录结构
      proton
                 |____ tools
                 |____ module_1_excel
                 |____ module_2_excel
                 |____ modele_xxx

这个该怎么修改呢？

**Comment by yanghuan** [comment]
__export.py  是配置导出文件列表的，里面有实际python解释器以及proto.py文件的路径

https://github.com/yanghuan/proton/blob/master/sample/__export.py#L26
你可以修改26，27行来改变tools的目录位置

**Comment by scc172fly** [comment]
我这么修改不行，比如说当前目录的上级目录改怎么修改，可以给个 demo 么？
python 小白。谢谢！能力有限，想把配置和工具分离，没能解决。
exportscript = '../../proton/excel/tools/proton.py'     
pythonpath = '../../proton\excel\tools\Python33/python.exe ' if platform.system() == 'Windows' else 'python '

**Comment by scc172fly** [comment]
我这么修改不行，比如说当前目录的上级目录改怎么修改，可以给个 demo 么？
python 小白。谢谢！能力有限，想把配置和工具分离，没能解决。这样配置的话是否需要设置环境变量？本机已经装了 2.7 的版本。
exportscript = '../../proton/excel/tools/proton.py'     
pythonpath = '../../proton\excel\tools\Python33/python.exe ' if platform.system() == 'Windows' else 'python '

**Comment by yanghuan** [comment]
父目录需要这么配置
'..\\..\\' 你试试
