### ISSUE TITLE
想请教一下，能不能单独获取某个配置表信息

### ISSUE THREAD

**Issue by Wecica** [yanghuan/proton#9]
目前的配置加载是一次把所有的配置都读出来，而且每个配置表都要人为添加Manager类，我想每次需要配置的时候读取某个特定配置，应该怎么做？

**Comment by yanghuan** [comment]
Manager类指的是C#读取代码的框架吗?  里面是个单例模式，可以根据需要改成惰性初始化

**Comment by Wecica** [comment]
嗯，我是想不用Manager类，直接Template里面包含自身的list。这样可以不用每个配置表都写一个Manager类，表多了很烦。。。关于嵌套先不考虑。

**Comment by yanghuan** [comment]
这个可以更具自己的需要去掉Manager框架。我都会使用这个框架来管理，配置表很多时候是需要检查错误，重新组织结构，使用派生类扩展，Manager中也可以放置一些公共函数。这个根据项目情况和自身使用习惯就行。

**Comment by Wecica** [comment]
好的，我试着根据需求改一下。
